### ISSUE TITLE
打开卡顿信息闪退

### ISSUE THREAD

**Issue by kllkko** [Knight-ZXW/BlockCanaryX#21]
小米13 澎湃OS  Android14

`                                                                                                    java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to com.knightboost.stacksampler.StackTraceSample
                                                                                                    	at com.knightboost.stacksampler.util.FlameGraphUtil.toFlameGraphText(FlameGraphUtil.java:35)
                                                                                                    	at blockcanary.ui.BlockListActivity$onBlocksRetrieved$1$1$1.run(BlockListActivity.kt:105)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)`

**Comment by Knight-ZXW** [comment]
手上没这个机型，可以尝试调试看下是什么原因

**Comment by guozhiqiang123** [comment]
> 手上没这个机型，可以尝试调试看下是什么原因

是混淆导致的，不混淆没得问题
